export const SECTIONS = [
  { id: 'search-section', label: 'Search', shortcut: 'Alt+1' },
  { id: 'search-location-section', label: 'Location', shortcut: 'Alt+2' },
  { id: 'match-type-section', label: 'Match Type', shortcut: 'Alt+3' },
  { id: 'file-size-section', label: 'File Size', shortcut: 'Alt+4' },
  { id: 'days-ago-section', label: 'Days Ago', shortcut: 'Alt+5' },
  { id: 'extensions-section', label: 'Extensions', shortcut: 'Alt+6' },
  { id: 'ignored-dirs-section', label: 'Ignored Dirs', shortcut: 'Alt+7' },
  { id: 'templates-section', label: 'Templates', shortcut: 'Alt+8' },
  { id: 'exclude-folders-section', label: 'Exclude Folders', shortcut: 'Alt+9' },
];

export const DEFAULTR_IGNORED_DIRS = [
  'node_modules',
  '.git',
  '.vite',
  '.next',
  'dist',
  '.dist',
  'generated',
  'cache',
  '.cache',
  'build',
  '.build',
  'target',
  'vendor',
  'public',
  'static',
  'venv',
  'cache',
  '.cache',
];

export const COMMON_FOLERS = ['src', 'docs', 'tests', 'assets', 'scripts'];

export const COMMON_EXTENSIONS = [
  'js',
  'ts',
  'jsx',
  'tsx',
  'css',
  'scss',
  'html',
  'md',
  'json',
  'yaml',
  'yml',
  'py',
  'rb',
  'go',
  'rs',
  'java',
  'php',
  'c',
  'cpp',
  'h',
  'sh',
  'txt',
];

export const COMMON_FOLDERS = [
  'node_modules',
  'dist',
  '.git',
  'build',
  'coverage',
  'tmp',
  'temp',
  'logs',
  'public',
  'assets',
  'vendor',
  'public',
  'static',
  'venv',
  'cache',
  '.cache',
  '.vscode',
  '.idea',
];
